name: gamenow_setup
description: Instalador de GameNow para Windows.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^4.0.7
  flutter:
    sdk: flutter
  path: ^1.9.1
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/vortex-256.png
    - assets/payload.zip
    - assets/header.webp
    - assets/logo.png
    - UI/uninstall.html
    - UI/style.css
    - UI/assets/logo.svg
    - UI/assets/672903.jpg
    - UI/assets/672904.jpg
  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora-Regular.ttf
          weight: 400
        - asset: fonts/Sora-SemiBold.ttf
          weight: 600
